In [7]:
import pandas as pd
from datetime import datetime
import numpy as np
from sqlalchemy import create_engine

# Configuration

In [8]:
CSV_FILE = "C:\projects\etl_csv_to_mysql\data\sales.csv"

MYSQL_USER = "root"
MYSQL_PASSWORD = "Adity@234892"
MYSQL_HOST = "localhost"
MYSQL_PORT = "3306"
MYSQL_DATABASE = "sales_db"
TARGET_TABLE = "etl_transformed_sales"

## DataBase Connection

In [9]:
# SQLALchemy Connection String 
conn_str = (
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

c:\Users\aryan\anaconda3\python.exe

In [5]:
!pip install pymysql

Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [6]:
import pymysql
print(pymysql.__version__)

2.2.8

In [10]:
# Create SQLALchemy Engine 

engine = create_engine(conn_str)

# Read CSV (Extract)

In [11]:
try:
    df = pd.read_csv(CSV_FILE)
    print("Data Extracted from {CSV_FILE} , shape = {df.shape}")
    display(df.head())
except Exception as e:
    print(f"Error loading CSV",{e})
    raise

Data Extracted from {CSV_FILE} , shape = {df.shape}

,OrderId,Product,Category,SalesAmount,OrderDate,Region,CustomerName
0,1001,Laptop Pro 13,Electronics,1000.0,2025-01-05,West,Alice Johnson
1,1002,Mechanical Keyboard,Electronics,95.5,2025-01-06,East,Bob Smith
2,1003,Desk Chair Ergonomic,Furniture,350.0,2025-01-06,West,Charlie Brown
3,1004,Coffee Maker Deluxe,Home Goods,150.0,2025-01-07,Central,Diana Prince
4,1005,Wireless Mouse,Electronics,25.0,2025-01-07,East,Evan Peters

# Transform

In [12]:
# Clean column names
df.columns = (
    df.columns
      .str.replace(' ', '_')
      .str.replace(r'([A-Z])', r'_\1', regex=True)
      .str.lower()
      .str.strip('_')
)

In [13]:
df

,order_id,product,category,sales_amount,order_date,region,customer_name
0,1001,Laptop Pro 13,Electronics,1000.00,2025-01-05,West,Alice Johnson
1,1002,Mechanical Keyboard,Electronics,95.50,2025-01-06,East,Bob Smith
2,1003,Desk Chair Ergonomic,Furniture,350.00,2025-01-06,West,Charlie Brown
3,1004,Coffee Maker Deluxe,Home Goods,150.00,2025-01-07,Central,Diana Prince
4,1005,Wireless Mouse,Electronics,25.00,2025-01-07,East,Evan Peters
5,1006,Monitor 27-inch 4K,Electronics,550.00,2025-01-08,West,Fiona Glenanne
6,1007,LED Desk Lamp,Home Goods,45.99,2025-01-08,South,George Costanza
7,1008,External SSD 1TB,Electronics,89.99,2025-01-09,Central,Hannah Montana
8,1009,Wood Bookshelf Small,Furniture,120.00,2025-01-09,South,Ian McKellen
9,1010,Gaming Headset,Electronics,-125.00,2025-01-10,East,Jasmine Teo

In [14]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [ ]:
df["order_date"]

AttributeError: type object 'type' has no attribute 'df'